# Generated by Django 6.0.4 on 2026-04-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idLocal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'locais',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('idResponsavel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'responsaveis',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idAmbiente', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('local', models.ForeignKey(db_column='local', on_delete=django.db.models.deletion.CASCADE, to='api.local')),
                ('responsavel', models.ForeignKey(db_column='responsavel', on_delete=django.db.models.deletion.CASCADE, to='api.responsavel')),
            ],
            options={
                'db_table': 'ambientes',
            },
        ),
        migrations.CreateModel(
            name='Microcontrolador',
            fields=[
                ('idMicro', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField()),
                ('ambiente', models.ForeignKey(db_column='ambiente', on_delete=django.db.models.deletion.CASCADE, to='api.ambiente')),
            ],
            options={
                'db_table': 'microcontroladores',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('idSensor', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador')], max_length=20)),
                ('unidade_med', models.CharField(choices=[('C', '°C'), ('%', '%'), ('lux', 'lux'), ('uni', 'uni')], max_length=10)),
                ('status', models.BooleanField()),
                ('mic', models.ForeignKey(db_column='mic', on_delete=django.db.models.deletion.CASCADE, to='api.microcontrolador')),
            ],
            options={
                'db_table': 'sensores',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('idHistorico', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('sensor', models.ForeignKey(db_column='sensor', on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
            options={
                'db_table': 'historicos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário')], max_length=10)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
